budget = {
    "count": 8,
    "next": null,
    "previous": null,
    "results": [{
            "objectid": 2,
            "table": "planRkab",
            "company": "lsa",
            "date": "2019-01-01",
            "inpit_volumea": 527000.0,
            "inpit_distance_a": 3179.0,
            "inpit_volume_b": 160000.0,
            "inpit_distance_b": 1700.0,
            "outpit_volume": null,
            "outpit_distance": null,
            "coalptr_tonage_a": 187500.0,
            "coalptr_distance_a": 18602.0,
            "coalptr_tonage_b": 48500.0,
            "coalptr_distance_b": 22244.0,
            "coalrtk_tonage": 187500.0,
            "coalbarging_tonage": 187500.0
        },
        {
            "objectid": 5,
            "table": "planBudget",
            "company": "lsa",
            "date": "2020-01-01",
            "inpit_volumea": 527000.0,
            "inpit_distance_a": 3179.0,
            "inpit_volume_b": 160000.0,
            "inpit_distance_b": 1700.0,
            "outpit_volume": null,
            "outpit_distance": null,
            "coalptr_tonage_a": 187500.0,
            "coalptr_distance_a": 18602.0,
            "coalptr_tonage_b": 45800.0,
            "coalptr_distance_b": 2224.0,
            "coalrtk_tonage": 187500.0,
            "coalbarging_tonage": 187500.0
        },
        {
            "objectid": 4,
            "table": "planRkab",
            "company": "lsa",
            "date": "2020-02-01",
            "inpit_volumea": 546000.0,
            "inpit_distance_a": 3239.0,
            "inpit_volume_b": 166000.0,
            "inpit_distance_b": 1730.0,
            "outpit_volume": null,
            "outpit_distance": null,
            "coalptr_tonage_a": 195200.0,
            "coalptr_distance_a": 19045.0,
            "coalptr_tonage_b": 45800.0,
            "coalptr_distance_b": 22252.0,
            "coalrtk_tonage": null,
            "coalbarging_tonage": null
        },
        {
            "objectid": 6,
            "table": "planBudget",
            "company": "lsa",
            "date": "2020-02-27",
            "inpit_volumea": 546000.0,
            "inpit_distance_a": 3239.0,
            "inpit_volume_b": 166000.0,
            "inpit_distance_b": 1730.0,
            "outpit_volume": null,
            "outpit_distance": null,
            "coalptr_tonage_a": 195200.0,
            "coalptr_distance_a": 19045.0,
            "coalptr_tonage_b": 45800.0,
            "coalptr_distance_b": 22252.0,
            "coalrtk_tonage": 195200.0,
            "coalbarging_tonage": 195200.0
        },
        {
            "objectid": 1,
            "table": "planBudget",
            "company": "scm",
            "date": "2019-01-01",
            "inpit_volumea": 316000.0,
            "inpit_distance_a": 2012.0,
            "inpit_volume_b": 20000.0,
            "inpit_distance_b": 5057.0,
            "outpit_volume": null,
            "outpit_distance": null,
            "coalptr_tonage_a": 134500.0,
            "coalptr_distance_a": 18440.0,
            "coalptr_tonage_b": null,
            "coalptr_distance_b": null,
            "coalrtk_tonage": null,
            "coalbarging_tonage": null
        },
        {
            "objectid": 3,
            "table": "planBudget",
            "company": "scm",
            "date": "2020-02-01",
            "inpit_volumea": 321000.0,
            "inpit_distance_a": 2090.0,
            "inpit_volume_b": 20000.0,
            "inpit_distance_b": 5057.0,
            "outpit_volume": null,
            "outpit_distance": null,
            "coalptr_tonage_a": 129500.0,
            "coalptr_distance_a": 18540.0,
            "coalptr_tonage_b": null,
            "coalptr_distance_b": null,
            "coalrtk_tonage": 134500.0,
            "coalbarging_tonage": 129500.0
        },
        {
            "objectid": 7,
            "table": "planRkab",
            "company": "scm",
            "date": "2020-03-17",
            "inpit_volumea": 500.0,
            "inpit_distance_a": 501.0,
            "inpit_volume_b": 502.0,
            "inpit_distance_b": 503.0,
            "outpit_volume": null,
            "outpit_distance": null,
            "coalptr_tonage_a": 505.0,
            "coalptr_distance_a": 506.0,
            "coalptr_tonage_b": 507.0,
            "coalptr_distance_b": 508.0,
            "coalrtk_tonage": 509.0,
            "coalbarging_tonage": 510.0
        },
        {
            "objectid": 8,
            "table": "planBudget",
            "company": "scm",
            "date": "2020-03-17",
            "inpit_volumea": 51.0,
            "inpit_distance_a": 52.0,
            "inpit_volume_b": 53.0,
            "inpit_distance_b": 54.0,
            "outpit_volume": 55.0,
            "outpit_distance": 56.0,
            "coalptr_tonage_a": 57.0,
            "coalptr_distance_a": 58.0,
            "coalptr_tonage_b": 59.0,
            "coalptr_distance_b": 60.0,
            "coalrtk_tonage": 61.0,
            "coalbarging_tonage": 62.0
        }
    ]
}

Actual = {
    "count": 4,
    "next": null,
    "previous": null,
    "results": [{
            "objectid": 3,
            "company": "lsa",
            "date": "2020-01-01",
            "inpit_volumea": 1001.0,
            "inpit_distance_a": 1002.0,
            "inpit_volume_b": 1003.0,
            "inpit_distance_b": 1004.0,
            "outpit_volume": 1005.0,
            "outpit_distance": 1006.0,
            "coalptr_all_tonage": 1007.0,
            "coalptr_all_distance": 1008.0,
            "coalptr_tonage_a": 1009.0,
            "coalptr_distance_a": 1010.0,
            "coalptr_tonage_b": 1011.0,
            "coalptr_distance_b": 1012.0,
            "coalptr_tonage_c": 1013.0,
            "coalptr_distance_c": 1014.0,
            "coalrtk_tonage": 1015.0,
            "coalbarging_tonage": 1016.0
        },
        {
            "objectid": 2,
            "company": "lsa",
            "date": "2020-03-15",
            "inpit_volumea": 500.0,
            "inpit_distance_a": 501.0,
            "inpit_volume_b": 502.0,
            "inpit_distance_b": 503.0,
            "outpit_volume": 504.0,
            "outpit_distance": 505.0,
            "coalptr_all_tonage": 506.0,
            "coalptr_all_distance": 507.0,
            "coalptr_tonage_a": 508.0,
            "coalptr_distance_a": 509.0,
            "coalptr_tonage_b": 510.0,
            "coalptr_distance_b": 511.0,
            "coalptr_tonage_c": 512.0,
            "coalptr_distance_c": 513.0,
            "coalrtk_tonage": 514.0,
            "coalbarging_tonage": 515.0
        },
        {
            "objectid": 1,
            "company": "scm",
            "date": "2020-01-01",
            "inpit_volumea": 10.0,
            "inpit_distance_a": 9.0,
            "inpit_volume_b": 8.0,
            "inpit_distance_b": 7.0,
            "outpit_volume": 6.0,
            "outpit_distance": 5.0,
            "coalptr_all_tonage": 4.0,
            "coalptr_all_distance": 3.0,
            "coalptr_tonage_a": 2.0,
            "coalptr_distance_a": 1.0,
            "coalptr_tonage_b": 10.0,
            "coalptr_distance_b": 9.0,
            "coalptr_tonage_c": 8.0,
            "coalptr_distance_c": 7.0,
            "coalrtk_tonage": 6.0,
            "coalbarging_tonage": 5.0
        },
        {
            "objectid": 4,
            "company": "scm",
            "date": "2020-01-01",
            "inpit_volumea": 200.0,
            "inpit_distance_a": 201.0,
            "inpit_volume_b": 202.0,
            "inpit_distance_b": 203.0,
            "outpit_volume": 204.0,
            "outpit_distance": 205.0,
            "coalptr_all_tonage": 206.0,
            "coalptr_all_distance": 207.0,
            "coalptr_tonage_a": 208.0,
            "coalptr_distance_a": 209.0,
            "coalptr_tonage_b": 210.0,
            "coalptr_distance_b": 211.0,
            "coalptr_tonage_c": 212.0,
            "coalptr_distance_c": 213.0,
            "coalrtk_tonage": 214.0,
            "coalbarging_tonage": 215.0
        }
    ]
}

agreed = {
    "count": 2,
    "next": null,
    "previous": null,
    "results": [{
            "company": "lsa",
            "date": "2020-03-17",
            "inpit_volume": 1001.0,
            "inpit_distance": 1002.0,
            "outpit_volume": 1003.0,
            "outpit_distance": 1004.0,
            "coalptr_all_tonage": 1005.0,
            "coalptr_all_distance": 1006.0
        },
        {
            "company": "scm",
            "date": "2020-03-17",
            "inpit_volume": 500.0,
            "inpit_distance": 501.0,
            "outpit_volume": 502.0,
            "outpit_distance": 503.0,
            "coalptr_all_tonage": 504.0,
            "coalptr_all_distance": 505.0
        }
    ]
}